"""
routers/messages.py
~~~~~~~~~~~~~~~~~~~
POST /sessions/{id}/messages — send a message and stream SSE response.

SSE event types emitted:
  message_delta    — streamed response tokens from the agent
  artifact_created — fired when Pi calls create_artifact
  done             — final event with message_id and skill_used
  error            — structured error (missing key, provider down, etc.)

The endpoint:
  1. Persists the user message.
  2. Validates the API key for the session's current provider (4xx if missing).
  3. Embeds the user query and runs hybrid retrieval (topic-tag pre-filter → vector).
  4. Passes full conversation history + retrieved context to Pi RPC.
  5. Accumulates the agent response, persists the assistant message, yields SSE.
"""

from __future__ import annotations

import json
import logging
import uuid
from typing import AsyncGenerator

import httpx
from fastapi import APIRouter, Depends, HTTPException, status, Request
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from ..config import settings
from ..database import get_db, get_session_factory
from ..models import (
    Artifact as ArtifactModel,
    Message as MessageModel,
    Session as SessionModel,
)
from ..pi_client import PiRPCError, pi_client
from ..schemas import MessageCreate
from .search import hybrid_search

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/sessions", tags=["messages"])

# ─── SSE helper ────────────────────────────────────────────────────────────────

def _sse(event_type: str, data: dict) -> str:
    """Format a single SSE event line."""
    return f"event: {event_type}\ndata: {json.dumps(data)}\n\n"


# ─── Tool execution (called from Python, not Pi) ────────────────────────────

async def _execute_tool(
    tool_name: str,
    args: dict,
    session_id: uuid.UUID,
    message_id: uuid.UUID,
    db_factory,
) -> tuple[str, dict | None]:
    """
    Execute a tool call dispatched by the Pi agent.

    Returns (result_text, artifact_dict | None).
    artifact_dict has keys: id, type, title, content — if an artifact was created.
    """
    if tool_name == "search_transcripts":
        query = args.get("query", "")
        results = await hybrid_search(query, top_k=5)
        formatted = "\n\n---\n\n".join(
            f"**{r['guest']} — {r['title']}**\n{r['content']}"
            for r in results
        )
        chunk_ids = [r["chunk_id"] for r in results]
        return formatted or "No relevant transcript passages found.", {"chunk_ids": chunk_ids}

    elif tool_name == "generate_ship30_essay":
        # The essay is generated by Pi's own LLM call using the system prompt
        # injected via the agent's tool definition. We just pass context back.
        topic = args.get("topic", "")
        context = args.get("source_context", "")
        return f"[Ship30 essay mode — topic: {topic}]\n\n{context}", None

    elif tool_name == "create_artifact":
        artifact_type = args.get("type", "markdown")
        title = args.get("title", "Untitled")
        content = args.get("content", "")

        async with db_factory() as db:
            artifact = ArtifactModel(
                message_id=message_id,
                session_id=session_id,
                type=artifact_type,
                title=title,
                content=content,
                version=1,
            )
            db.add(artifact)
            await db.commit()
            await db.refresh(artifact)

        return f"Artifact '{title}' created.", {
            "id": str(artifact.id),
            "type": artifact_type,
            "title": title,
            "content": content,
        }

    else:
        return f"[Unknown tool: {tool_name}]", None


# ─── SSE generator ─────────────────────────────────────────────────────────────

async def _stream_response(
    session: SessionModel,
    user_content: str,
    user_message_id: uuid.UUID,
) -> AsyncGenerator[str, None]:
    """
    Core streaming logic — yields raw SSE strings.

    Runs *outside* the normal request DB session because SSE generators
    outlive FastAPI's dependency lifetime; we use a fresh session factory.
    """
    db_factory = get_session_factory()

    # ── 1. Validate provider key ────────────────────────────────────────────
    provider = session.llm_provider
    try:
        api_key = settings.require_provider_key(provider)
    except ValueError as exc:
        yield _sse("error", {
            "code": "missing_api_key",
            "message": str(exc),
        })
        return

    # ── 2. Fetch conversation history ───────────────────────────────────────
    async with db_factory() as db:
        result = await db.execute(
            select(MessageModel)
            .where(MessageModel.session_id == session.id)
            .order_by(MessageModel.created_at)
        )
        history = result.scalars().all()

    messages = [{"role": m.role, "content": m.content} for m in history]

    # ── 3. Hybrid retrieval ─────────────────────────────────────────────────
    retrieved_chunk_ids: list[uuid.UUID] = []
    context_block = ""
    try:
        results = await hybrid_search(user_content, top_k=5)
        if results:
            retrieved_chunk_ids = [r["chunk_id"] for r in results]
            snippets = "\n\n---\n\n".join(
                f"**{r['guest']} — {r['title']}**\n{r['content']}"
                for r in results
            )
            context_block = (
                f"\n\n<retrieved_context>\n{snippets}\n</retrieved_context>\n\n"
            )
    except Exception as exc:
        logger.warning("Retrieval failed, continuing without context: %s", exc)

    # Inject retrieval context into the last user message
    if context_block and messages:
        messages[-1]["content"] = messages[-1]["content"] + context_block

    # ── 4. Stream Pi RPC ────────────────────────────────────────────────────
    full_response = ""
    skill_used: str | None = None
    pi_error: str | None = None

    # Resolve model/base_url for Ollama
    model = session.llm_model
    if provider == "ollama":
        # Pi uses the models.json for Ollama routing; pass the model name
        model = settings.ollama_model if model == "gpt-4o-mini" else model

    try:
        async for event in pi_client.run_turn(
            messages=messages,
            provider=provider,
            model=model,
            api_key=api_key,
            session_id=str(session.id),
            timeout_seconds=90.0,
        ):
            event_type = event.get("type")

            if event_type == "token":
                token = event.get("content", "")
                full_response += token
                yield _sse("message_delta", {"content": token})

            elif event_type == "tool_call":
                tool_name = event.get("tool", "")
                args = event.get("args", {})
                skill_used = tool_name

                tool_result, artifact_info = await _execute_tool(
                    tool_name,
                    args,
                    session_id=session.id,
                    message_id=user_message_id,
                    db_factory=db_factory,
                )

                if artifact_info and "id" in artifact_info:
                    yield _sse("artifact_created", {
                        "id": artifact_info["id"],
                        "type": artifact_info["type"],
                        "title": artifact_info["title"],
                        "content": artifact_info["content"],
                    })

            elif event_type == "done":
                full_response = event.get("content", full_response)
                skill_used = event.get("skill_used", skill_used)
                break

    except PiRPCError as exc:
        err_msg = str(exc)
        # Distinguish Ollama-specific errors
        if "ollama" in err_msg.lower() or "11434" in err_msg:
            user_msg = "Local model unavailable — is `ollama serve` running?"
        elif "api key" in err_msg.lower() or "unauthorized" in err_msg.lower():
            user_msg = f"API key error for provider '{provider}': {err_msg}"
        else:
            user_msg = f"Agent error: {err_msg}"

        yield _sse("error", {"code": "agent_error", "message": user_msg})
        pi_error = err_msg

    except Exception as exc:
        logger.exception("Unexpected error in SSE stream")
        yield _sse("error", {
            "code": "internal_error",
            "message": f"Unexpected error: {exc}",
        })
        pi_error = str(exc)

    # ── 5. Persist assistant message ────────────────────────────────────────
    if full_response or pi_error:
        async with db_factory() as db:
            assistant_msg = MessageModel(
                session_id=session.id,
                role="assistant",
                content=full_response or f"[Error: {pi_error}]",
                skill_used=skill_used,
                retrieved_chunk_ids=retrieved_chunk_ids,
            )
            db.add(assistant_msg)
            await db.commit()
            await db.refresh(assistant_msg)

        yield _sse("done", {
            "message_id": str(assistant_msg.id),
            "skill_used": skill_used,
        })


# ─── Endpoint ──────────────────────────────────────────────────────────────────

@router.post(
    "/{session_id}/messages",
    summary="Send a user message; streams SSE response",
)
async def post_message(
    session_id: uuid.UUID,
    body: MessageCreate,
    db: AsyncSession = Depends(get_db),
) -> StreamingResponse:
    # ── Resolve session ──────────────────────────────────────────────────────
    result = await db.execute(
        select(SessionModel).where(SessionModel.id == session_id)
    )
    session = result.scalar_one_or_none()
    if session is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Session {session_id} not found.",
        )

    # ── Validate API key before opening SSE (give a clear 4xx, not an SSE error)
    if session.llm_provider != "ollama":
        try:
            settings.require_provider_key(session.llm_provider)
        except ValueError as exc:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail={
                    "code": "missing_api_key",
                    "message": str(exc),
                    "provider": session.llm_provider,
                },
            )

    # ── Persist user message ─────────────────────────────────────────────────
    user_msg = MessageModel(
        session_id=session.id,
        role="user",
        content=body.content,
    )
    db.add(user_msg)
    await db.flush()
    await db.refresh(user_msg)

    return StreamingResponse(
        _stream_response(session, body.content, user_msg.id),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
